apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-classifier-deployment
  labels:
    app: text-classifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-classifier
  template:
    metadata:
      labels:
        app: text-classifier
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 128Mi
      containers:
      - name: text-classifier
        image: 776427377677.dkr.ecr.us-west-2.amazonaws.com/stevezheng23/tritonserver:21.10-py3-pt-transformers.55c63bcc75330174da52e3164aecae390dae3cbf.1855187944
        args: [
          "tritonserver",
          "--model-repository=/model_repository"
        ]
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: grpc
        - containerPort: 8002
          name: metrics
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        resources:
          limits:
            memory: 2Gi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: "0.25"
      imagePullSecrets:
        - name: text-classifier-ecr-secret
