apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: text-classifier
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stevezheng23/k8s.git
    targetRevision: HEAD
    path: deployment/text-classifier/eks/app
  destination:
    server: https://kubernetes.default.svc
    namespace: text-classifier
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
